# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

NumPy no pertenece al _core_ de Python y es por eso que debemos importarlo para poder usarlo. 

Para importar una libreria en Python se usa la siguiente sintaxis:
    
`import libreria as alias`

Para importar una funcion en particular de un modulo o libreria, utilizamos la sintaxis:
    
`from libreria import funcion`

Como convencion, cuando se importa `numpy` se le asigna el alias `np`. Pero esto no es obligatorio, solo me facilita muchas veces la escritura del codigo.

In [109]:
#Importar numpy 
import numpy as np

De ahora en mas para utilizar una función de Numpy solo tengo que usar `np` y luego llamar función. Por ejemplo, si quiero llamar la función `.mean()`, debo escribir: `np.mean()`.

Comenzemos a ver que funciones se pueden utilizar en NumPy.

- `.array()`

Esta función me permite crear un array. Es posible crear arrays a partir de listas.

In [110]:
#creo un array
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [111]:
#crea una lista llamada mi_lista que contenga 10 numeros

mi_lista = [45,123,89,3,45,2,99,56,34,10]

#Ahora transforma tu lista en un array usando np.array y asignalo a la variable mi_array

mi_array = np.array(mi_lista)
#Imprimi mi_array
print(mi_array)

[ 45 123  89   3  45   2  99  56  34  10]


Podemos usar `type` para obtener el tipo de estructura de datos que estamos trabajando.

In [112]:
#Aplica type sobre mi_array para mostrar que tipo de estructura de datos es
type(mi_array)


numpy.ndarray

Los arrays y las listas se comportan diferente frente operaciones matematicas con números.

In [113]:
#Corre el siguiente codigo
print(mi_lista + 2)

TypeError: can only concatenate list (not "int") to list

No es posible sumar un numero a cada uno de los elementos de una lista. Sin embargo, esto funciona distinto en Numpy.

In [ ]:
#Suma 2 a cada elemento de mi_array
mi_lista2 = [i + 2 for i in mi_lista]

print(mi_lista2)

[47, 125, 91, 5, 47, 4, 101, 58, 36, 12]


El comportamiento tambien es distinto para la operacion de multiplicacion.

In [ ]:
#Corre el siguiente codigo y fijate que pasa
print(mi_lista * 2) 

[45, 123, 89, 3, 45, 2, 99, 56, 34, 10, 45, 123, 89, 3, 45, 2, 99, 56, 34, 10]


In [ ]:
#Ahora multiplica por dos cada elemento de mi_array

mi_lista3 =  [i * 2 for i in mi_lista]

print(mi_lista3)

[90, 246, 178, 6, 90, 4, 198, 112, 68, 20]


Los arrays y las listas se comportan diferente frente a operaciones con otros arrays/listas

In [ ]:
#Corre el siguiente codigo
lista1 = [1, 2, 3, 4, 5]
lista2 = [5, 4, 3, 2, 1]

arr1 = np.array(lista1)
arr2 = np.array(lista2)

In [ ]:
#Concatena las dos listas
lista1 + lista2

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

In [ ]:
#Suma los elementos de los dos arrays

lista3 = []
for i in lista1:
     for j in lista2:
           lista3.append(i + j)
print(lista3)

lista1 = [1,2,3,4]
lista2 = [9,2,3,4]

array1 = np.array(lista1)
array2 = np.array(lista2)
  
print(array1 + array2)

[6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 8, 7, 6, 5, 4, 9, 8, 7, 6, 5, 10, 9, 8, 7, 6]
[10  4  6  8]


In [ ]:
#Multiplica los elementos de cada arreglo
print(array1 * array2)

[ 9  4  9 16]


In [ ]:
#Resta los dos arrays
print(array1 - array2)

[-8  0  0  0]


In [ ]:
#Dividi los dos arrays
print(array1 / array2)

[0.11111111 1.         1.         1.        ]


In [ ]:
#Eleva el array1 al array2
print(array2**array1)

[  9   4  27 256]


Para acceder a los elementos de los arrays de una dimension se utilizan los indices como las listas.

In [ ]:
#Corre el siguiente codigo
print(lista1[0], arr1[0]) 

1 1


In [ ]:
#Obtene el 3er elemento de arr1
print(lista1[2], arr1[2])

3 3


In [ ]:
#Obtene el 5to elemento de arr2
print (lista2[4], arr2[4])

1 1


In [ ]:
#Obtene el ultimo elemento de arr1
print (lista1[4], array2[3])

5 4


Asi tambien obtenemos una porción del array de la misma manera que obtenemos una parte de una lista. A su vez podemos reasignar nuevos valores a una porción del array.

In [ ]:
#Corre el siguiente codigo
lista1 = [1,2,3,4]
lista2 = [9,2,3,4]

array1 = np.array(lista1)
array2 = np.array(lista2)

array1[1:4] = [22, 23, 24]

In [ ]:
#Imprimi el arr1
print(array1)
print(arr1)

[ 1 22 23 24]
[1 2 3 4 5]


## Arreglos multidimensionales

Las listas son cadenas unidimensionales de elementos. Los arreglos pueden ser multidimensionales. Para comprender mejor que son, miremos el siguiente ejemplo:

In [ ]:
#Corre el siguiente codigo
lista = [[0, 1, 3], [3, 4, 5]]
arr2d = np.array(lista)
arr2d

array([[0, 1, 3],
       [3, 4, 5]])

In [ ]:
#Veamos cuantas dimensiones tiene el array
print(arr2d.ndim)

2


In [ ]:
#Veamos cuantos elementos tiene el array
print(arr2d.size)

6


In [ ]:
#Arma ahora un array de 3 dimensiones.
coso = [[[2,4,6],[1,3,5],[8,10,12]]]
arr3d = np.array(coso)
arr3d

array([[[ 2,  4,  6],
        [ 1,  3,  5],
        [ 8, 10, 12]]])

In [ ]:
#Chequea usando ndim que efectivamente tenga tres dimensiones
print(arr3d.ndim)

3


**¿Como accedemos entonces a un array de mas de una dimension?**

In [ ]:
#definamos un nuevo array
lista2 = [[0, 1, 3], [3, 4, 5], [9, 10, 4], [2, 5, 6]]
nuevo_array = np.array(lista2)

¿Cuantas dimensiones tiene el array `nuevo_array`? Comprobalo usando `ndim`.

In [ ]:
#Dimensiones de nuevo_array
print(nuevo_array.ndim)

2


In [ ]:
#Mostra nuevo_array
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


Si para un array de 1 dimension, usabamos un indice, para un array de n dimensiones tenemos que usar n indices. En el caso de 2 dimensiones, usaremos 2 indices. El primero indica la fila y el segundo la columna.

In [ ]:
#Corre el siguiente codigo
print(nuevo_array[0,1])

1


In [ ]:
#Accede al tercer elemento de la segunda fila de nuevo_array
print(nuevo_array[1,2])

5


In [121]:
#Accede al segundo elemento de la fila 0 de nuevo_array
print(nuevo_array[0,1])

1


In [ ]:
#Accede al cuarto elemento de la segunda columna de nuevo_array
print(nuevo_array[3,2])

6


In [ ]:
#Accedo a toda la segunda columna
nuevo_array[:, 1]

array([ 1,  4, 10,  5])

In [ ]:
#Accede a un subarray que vaya desde el segundo elemento de la 
#primer fila hasta el segundo elemento de la tercer 
#fila de nuevo_array
print(nuevo_array[: , 2])

[3 5 4 6]


In [131]:
#Accede a un subarray que vaya desde el primer elemento de la 
#segunda fila hasta el segundo elemento de la cuarta 
#fila de nuevo_array
print(nuevo_array[1 , :2], nuevo_array[2 , :2], nuevo_array[3 , :2])

[3 4] [ 9 10] [2 5]


array([[ 3,  4],
       [ 9, 10],
       [ 2,  5]])

## Creación de arreglos

- **np.zeros(shape, dtype, order)**: Crea un array con todos ceros en sus posiciones

In [ ]:
#Corre el siguiente codigo
print(np.zeros((2, 2, 2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


- **np.ones(shape, dtype, order)**: Crea un array con todos unos en sus posiciones

In [ ]:
#Corre el siguiente codigo
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


- **np.random.rand(d0, d1, ..., dn)**: Genera un array con valores al azar con una distribución `[0, 1)` y segun las dimensiones pasada como argumento.

In [ ]:
#Genera un array con valores al azar
print(np.random.randn(10))

[-1.06824336  1.46558903 -0.89104976  0.07511245 -0.52990401  0.57912369
  0.14175476 -0.82435155 -0.28920658  1.60562425]


- **np.random.randint(low, high, size)**: Devuelve un array con enteros al azar. Cuando se especifica un solo entero como argumento este entero es entendido como el mayor valor que ese numero random puede tomar. Si se pasan dos, uno es el menor valor y el otro es el mayor valor. Con size se le puede decir que dimensiones tiene el array. Si no le paso ningun valor, devolvera solo un numero entero.

In [132]:
#Genera un array con enteros al azar
np.random.randint(5)

1

- **np.arange([start, ]stop, [step, ])**: Devuelve numero simetricamente distribuidos segun los valores datos. El primer valor es el comienzo, el segundo el final y el tercero representa cada cuanto queremos esos valores.

In [ ]:
#Corre esta linea de codigo y comprende como funciona np.arange
np.arange(2, 16, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

## Funciones estadisticas

NumPy nos facilita varias funciones que nos permitiran obtener algunos parametros estadisticos de nuestros arrays. Veamos cuales son estas funciones.

In [ ]:
#Volvamos a ver como era nuestro array nuevo_array
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


- `np.mean()`: Media o Promedio.

In [ ]:
#usa la funcion mean para obtener el promedio de los valores en nuevo_array
np.mean(nuevo_array)

4.333333333333333

- `np.var()`: Devuelve la dispersión de los valores alrededor de la media

In [ ]:
#usa la funcion var para obtener la varianza de los valores en nuevo_array
np.var(nuevo_array)

8.055555555555557

- `np.sum()`: devuelve la suma de todos los valores en el array. 
- `np.min()`: devuelve el menor valor en el array
- `np.max()`: devuelve el maximo valor en el array

In [138]:
#Muestra la suma de los valores en nuevo_array
print(np.sum(nuevo_array))

#Muestra el minimo y maximo valor en nuevo array

print(np.min(nuevo_array))
print(np.max(nuevo_array))

52
0
10
